[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/start.sh"
restartPolicyType = "always"

[deploy.env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:${RAILWAY_RANDOM_KEY}"
APP_URL = "https://${RAILWAY_STATIC_URL}"
ASSET_URL = "https://${RAILWAY_STATIC_URL}"
LOG_CHANNEL = "stderr"
DB_CONNECTION = "mysql"
DB_HOST = "${DB_HOST}"
DB_PORT = "${DB_PORT}"
DB_DATABASE = "${DB_DATABASE}"
DB_USERNAME = "${DB_USERNAME}"
DB_PASSWORD = "${DB_PASSWORD}"
