[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/start.sh"
restartPolicyType = "always"

[deploy.env]
APP_ENV = "production"
APP_DEBUG = "true"
APP_KEY = "base64:${RAILWAY_RANDOM_KEY}"
APP_URL = "https://${RAILWAY_STATIC_URL}"
ASSET_URL = "https://${RAILWAY_STATIC_URL}"
LOG_CHANNEL = "stderr"
DB_CONNECTION = "mysql"
DB_HOST = "${RAILWAY_PRIVATE_DOMAIN}"
DB_PORT = "3306"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"
